name: iTag
version: ${project.build.version}
description: Name tag API which is backwards compatible with TagAPI
authors: [md_5, Postremus]
load: STARTUP
main: org.kitteh.tag.TagAPI
depend: [ProtocolLib]
